name: lacework-iac-scan-pr
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch
 pull_request:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  Lacework-Scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lacework IaC Scan
        id: laceworkscan
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
          LW_SUBACCOUNT: ${{ secrets.LW_ACCOUNT_NAME }}
        run: |
          # Setup
          IAC_REPORTS_DIR="/tmp/iac_reports"
          env | grep "GITHUB_\|LW_\|CI_" > env.list    # Set Lacework and other secrets
          echo "WORKSPACE=src" >> env.list            
          echo "JUNIT_OUTPUT_FILE=/tmp/lacework-report.junit.xml"  >> env.list
          echo "JSON_OUTPUT_FILE=/tmp/lacework-report.json"  >> env.list

          # Run the Scan
          docker run --env-file env.list -v "$(pwd):/app/src"  -w /app/src lacework/codesec:stable lacework iac scan

          # Copy the report outside lacework/codesec-iac:latest container
          CONTAINER_ID=$(docker ps -a |grep lacework |head -n1 |cut -d ' ' -f1) # Extracts the latest container ID (Inside a pipeline there should be only one anyways)
          mkdir $IAC_REPORTS_DIR
          docker container cp "$CONTAINER_ID:/tmp/lacework-report.json" $IAC_REPORTS_DIR
 
          # Set GITHUB_ENV
          RESULTS_JSON="$IAC_REPORTS_DIR/lacework-report.json"
          echo "RESULTS_JSON=$RESULTS_JSON" >> "$GITHUB_ENV"
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { TESTS, TESTS_PASSED, TESTS_FAILED   } = process.env
            const message = "Verify the Lacework IaC scanning results before merging!"
            const test_results = `<table><tr><th><th>Tests</th><th>Passed ✅</th><th>Failed ❌</th></tr><tr><td>Lacework TF-SCAN JUnit Results</td><td>${TESTS} Ran</td><td>${TESTS_PASSED} Passed</td><td>${TESTS_FAILED} Failed</td></tr></table>`
            const output = message + test_results
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })